version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysqlpass'
    ports:
      - "3306:3306"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
